### ISSUE TITLE
Problem on delete photos

### ISSUE THREAD

**Issue by miscelatore** [rapind/albumdy#6]
Hi,

I tried to use your photo gallery with postgresql database.
When I try to delete some photos I get the following error message:

Processing Admin::PhotosController#destroy (for 127.0.0.1 at 2011-01-21 14:35:10) [DELETE]
  Parameters: {"album_id"=>"test", "action"=>"destroy", "_method"=>"delete", "authenticity_token"=>"kuABs2Q1dTTWpnuSYmo+X25fatKYwQ2ctJT/5bVhpDc=", "id"=>"valentino-rossi", "controller"=>"admin/photos"}
  Administrator Load (1.6ms)   SELECT \* FROM "administrators" LIMIT 1
  Administrator Load (0.4ms)   SELECT \* FROM "administrators" WHERE ("administrators"."id" = E'1') LIMIT 1
  Album Load (0.6ms)   SELECT \* FROM "albums" WHERE ("albums"."cached_slug" = E'test') LIMIT 1
  Administrator Load (0.2ms)   SELECT \* FROM "administrators" WHERE ("administrators"."id" = 1) 
  Photo Load (0.6ms)   SELECT \* FROM "photos" WHERE ("photos".album_id = 5) AND ("photos"."cached_slug" = E'valentino-rossi') ORDER BY position LIMIT 1
  SQL (0.1ms)   BEGIN
  Photo Update (0.3ms)   UPDATE "photos" SET position = (position - 1) WHERE (album_id = 5 AND position > 2) 
  Slug Load (0.5ms)   SELECT \* FROM "slugs" WHERE ("slugs".sluggable_id = 57 AND "slugs".sluggable_type = E'Photo') ORDER BY id DESC, id DESC LIMIT 1
  Photo Update (0.0ms)   PGError: ERROR: null value in column "position" violates not-null constraint
: UPDATE "photos" SET "updated_at" = '2011-01-21 13:35:10.063112', "position" = NULL WHERE "id" = 57
  SQL (0.0ms)   ROLLBACK

ActiveRecord::StatementInvalid (PGError: ERROR:  null value in column "position" violates not-null constraint
: UPDATE "photos" SET "updated_at" = '2011-01-21 13:35:10.063112', "position" = NULL WHERE "id" = 57):
  /Library/Ruby/Gems/1.8/gems/acts_as_list-0.1.2/lib/acts_as_list.rb:124:in `remove_from_list'
  /Library/Ruby/Gems/1.8/gems/inherited_resources-0.9.5/lib/inherited_resources/base_helpers.rb:86:in`destroy_resource'
  /Library/Ruby/Gems/1.8/gems/inherited_resources-0.9.5/lib/inherited_resources/actions.rb:64:in `destroy!'
  app/controllers/admin/photos_controller.rb:27:in`destroy'
  haml (2.2.19) rails/./lib/sass/plugin/rails.rb:19:in `process'

Any suggestions?

Tanks
Stefano

**Comment by rapind** [comment]
This should be fixed now. The problem was the non-null constraint on the position fields. The way acts_as_list works with postgresql doesn't play nice with those constraints. Update and rerun your migrations to fix.
